### PR TITLE
Replacing matlab with python evaluation

### PR DESCRIPTION
**Pull request by senthilps8**
- Replaced the matlab evaluation with python code
- Uses the annotation cache files generated by the VOCdevkit

### CODE REVIEW

**Comment by alantrrs** [comment]
Does this mean I should be able to train on the VOT dataset without the
``EnvironmentError: MATLAB command 'matlab' not found. Please add 'matlab' to your PATH.`` error?

I'm trying to test but I still get the error. Is this still planned to be merged?

**Comment by senthilps8** [comment]
Should be fixed now.
You would still need to have the annotation mat files (train_anno.mat, trainval_anno.mat, test_anno.mat) in the $FRCN_ROOT/data/VOCdevkit2007/local/VOC<year>/  folder.
If you can't generate them yourself, I think the ones available here(http://vision.cs.utexas.edu/voc/local/) should work.

**Comment by deshelv** [comment]
How to generate the annotation mat files if I'm going to use VOC2012 dataset?

**Comment by rbgirshick** [comment]
Thanks! This issue is fixed in https://github.com/rbgirshick/py-faster-rcnn/commit/45e0da9a246fab5fd86e8c96dc351be7f145499f.

**Pull request closed without merging**
